# pylint: disable=wrong-import-order, invalid-name, attribute-defined-outside-init

"""The module halftest.blog.view.post_comment provides the PostComment class.

WARNING!

This file is part of the halftest package. It has been generated by the
command hop. To keep it in sync with your database structure, just rerun
hop update.

More information on the half_orm library on https://github.com/collorg/halfORM.

DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOUR CODE GOES BETWEEN THESE LINES OR AT THE END OF THE FILE.
hop ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from half_orm.model import register
from halftest import MODEL, ho_dataclasses
fields_aliases=None
#>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!

#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

@register
class PostComment(MODEL.get_relation_class('blog.view.post_comment', fields_aliases=fields_aliases)):
    """
    DATABASE: halftest
    SCHEMA: blog.view
    VIEW: post_comment

    DESCRIPTION:
    This view joins: - comment, - author of the comment, - post, - author of the post.
    FIELDS:
    - post_title:                (text)
    - author_post_id:            (int4)
    - author_post_first_name:    (text)
    - author_post_last_name:     (text)
    - comment_id:                (int4)
    - comment_content:           (text)
    - post_id:                   (int4)
    - author_comment_id:         (int4)
    - author_comment_first_name: (text)
    - author_comment_last_name:  (text)

    """
    #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
    #<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!
    #pylint: disable=line-too-long, too-many-arguments, redefined-builtin, too-many-positional-arguments
    def __init__(self, post_title: 'str'=None, author_post_id: 'int'=None, author_post_first_name: 'str'=None, author_post_last_name: 'str'=None, comment_id: 'int'=None, comment_content: 'str'=None, post_id: 'int'=None, author_comment_id: 'int'=None, author_comment_first_name: 'str'=None, author_comment_last_name: 'str'=None, **kwargs):
        super().__init__(post_title=post_title, author_post_id=author_post_id, author_post_first_name=author_post_first_name, author_post_last_name=author_post_last_name, comment_id=comment_id, comment_content=comment_content, post_id=post_id, author_comment_id=author_comment_id, author_comment_first_name=author_comment_first_name, author_comment_last_name=author_comment_last_name, **kwargs)

        #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
