# pylint: disable=wrong-import-order, invalid-name, attribute-defined-outside-init

"""The module halftest.blog.event provides the Event class.

WARNING!

This file is part of the halftest package. It has been generated by the
command hop. To keep it in sync with your database structure, just rerun
hop update.

More information on the half_orm library on https://github.com/collorg/halfORM.

DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOUR CODE GOES BETWEEN THESE LINES OR AT THE END OF THE FILE.
hop ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from half_orm.model import register
from halftest import MODEL, ho_dataclasses
fields_aliases=None
#>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!

#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

@register
class Event(MODEL.get_relation_class('blog.event', fields_aliases=fields_aliases)):
    """
    DATABASE: halftest
    SCHEMA: blog
    TABLE: event

    DESCRIPTION:
    The table blog.event contains all the events of the blogging system. It inherits blog.post. It's just here to illustrate the inheriance in half_orm
    FIELDS:
    - id:                (int4) NOT NULL
    - title:             (text)
    - content:           (text)
    - author_first_name: (text)
    - author_last_name:  (text)
    - author_birth_date: (date)
    - data:              (jsonb)
    - begin:             (timestamp)
    - end:               (timestamp)
    - location:          (text)

    PRIMARY KEY (id)
    FOREIGN KEY:
    - author: ("author_first_name", "author_last_name", "author_birth_date")
     ↳ "halftest":"actor"."person"(first_name, last_name, birth_date)

    To use the foreign keys as direct attributes of the class, copy/paste the Fkeys below into
    your code as a class attribute and replace the empty string key(s) with the alias(es) you
    want to use. The aliases must be unique and different from any of the column names. Empty
    string keys are ignored.

    Fkeys = {
        '': 'author',
    }
    """
    #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
    Fkeys = {
        'author_fk': 'author'
    }
    #<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!
    #pylint: disable=line-too-long, too-many-arguments, redefined-builtin, too-many-positional-arguments
    def __init__(self, id: 'int'=None, title: 'str'=None, content: 'str'=None, author_first_name: 'str'=None, author_last_name: 'str'=None, author_birth_date: 'date'=None, data: 'typing.Any'=None, begin: 'datetime'=None, end: 'datetime'=None, location: 'str'=None, **kwargs):
        super().__init__(id=id, title=title, content=content, author_first_name=author_first_name, author_last_name=author_last_name, author_birth_date=author_birth_date, data=data, begin=begin, end=end, location=location, **kwargs)

        #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
